name: cynnexis/latex CI/CD

on:
  push:
    branches:
      - main
      - 'cicd/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build the Docker image and send it to Docker Hub
    timeout-minutes: 180
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare files for production
        run: DEBUG=false make --no-print-directory texlive.profile
      - name: Get the project version
        run: |
          project_version=$(cat VERSION)
          echo "project_version=$project_version" >> $GITHUB_ENV
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build image
        id: build_image
        uses: docker/build-push-action@v2
        with:
          tags: |
            cynnexis/latex:latest
            cynnexis/latex:${{ env.project_version }}
          load: true
          context: .
          build-args: PROJECT_VERSION="${{ env.project_version }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Inspect built image
        run: |
          echo "Image ID:              ${{ steps.build_image.outputs.imageid }}"
          echo "Image digest:          ${{ steps.build_image.outputs.digest }}"
          echo "Build result metadata: ${{ steps.build_image.outputs.metadata }}"

      # Test built image
      - name: Test the Docker image
        run: make test

      # Detect vulnerabilities with Snyk
      - name: Run Snyk to check Docker image for vulnerabilities
        # Snyk can be used to break the build when it detects vulnerabilities.
        # In this case we want to upload the issues to GitHub Code Scanning
        continue-on-error: true
        uses: snyk/actions/docker@7fad562681122205233d1242c3bb39598c5393da
        env:
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://github.com/snyk/actions#getting-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: cynnexis/latex:${{ env.project_version }}
          args: --file=Dockerfile
          json: true
          sarif: true
      - name: Upload Snyk result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      - name: Upload Snyk SARIF result as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snyk.sarif
          path: snyk.sarif
      - name: Upload Snyk JSON result as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snyk.json
          path: snyk.json

      # Push images
      - name: Push image to Docker registry
        if: github.event_name == 'pull_request' && github.base_ref == 'main' || contains(github.ref, 'cicd/')
        run: docker push --all-tags cynnexis/latex
      - name: Push image to multiple registries
        if: github.event_name == 'pull_request' && github.base_ref == 'main' || contains(github.ref, 'cicd/')
        # Copy image from Docker Hub to ghcr after tests (source: https://github.com/docker/build-push-action/blob/master/docs/advanced/copy-between-registries.md)
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/cynnexis/latex:${{ env.project_version }}
          dst: |
            ghcr.io/cynnexis/latex:latest
            ghcr.io/cynnexis/latex:${{ env.project_version }}

  test-gh-action:
    runs-on: ubuntu-20.04
    name: Test the GitHub Action Cynnexis/cynnexis-latex
    needs:
      - build
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Cynnexis/cynnexis-latex
        uses: ./
        with:
          engine: pdflatex
          file: test/document.tex
      - name: Check the results
        run: |
          [[ -f document.pdf ]]

  release:
    runs-on: ubuntu-20.04
    name: Create a release
    timeout-minutes: 5
    needs:
      - test-gh-action
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the project version
        run: |
          project_version=$(cat VERSION)
          echo "project_version=$project_version" >> $GITHUB_ENV
      - name: Create a release for the Docker image
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.project_version }}
          release_name: ${{ env.project_version }}
          body: "Ref: ${{ github.ref }} SHA: ${{ github.sha }}"
          draft: true
          prerelease: false
