name: cynnexis/latex CI/CD

on:
  push:
    branches:
      - master
      - 'cicd/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build the Docker image and send it to Docker Hub
    if: github.event_name == 'pull_request' && github.base_ref == 'master' || contains(github.ref, 'cicd/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare files for production
        run: cp config/texlive.prod.profile texlive.profile
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          repository: cynnexis/latex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
      - name: Test the Docker image
        run: make test
  
  release:
    runs-on: ubuntu-18.04
    name: Create a release
    needs: build
    if: github.event_name == 'pull_request' && github.base_ref == 'master' || github.event_name == 'push' && contains(github.ref, 'master') || contains(github.ref, 'cicd/')
    steps:
      - name: Create a release for the Docker image
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }}
          body: "Ref: ${{ github.ref }} SHA: ${{ github.sha }}"
          draft: true
          prerelease: false
