name: cynnexis/latex CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build the Docker image and send them to registries
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          repository: cynnexis/latex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
