name: cynnexis/latex CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build the Docker image and send them to registries
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          repository: cynnexis/latex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
      - name: Tag Docker image for GitHub Packages
        run: docker tag cynnexis/latex docker.pkg.github.com/cynnexis/cynnexis-latex/cynnexis/latex:latest
      - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          repository: docker.pkg.github.com/cynnexis/cynnexis-latex/cynnexis/latex
          username: ${{ secrets.GIT_HUB_USERNAME }}
          password: ${{ secrets.GIT_HUB_PASSWORD }}
          tags: latest
          registry: docker.pkg.github.com
