name: cynnexis/latex CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build the Docker image from the Dockerfile.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to Docker Hub
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: cynnexis/latex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tagging: true
      - name: Publish to GitHub Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: cynnexis/latex
          username: ${{ secrets.GIT_HUB_USERNAME }}
          password: ${{ secrets.GIT_HUB_PASSWORD }}
          dockerfile: Dockerfile
          registry: docker.pkg.github.com
          tagging: true
